name: Github Actions Demo
run-name: ${{ github.actor }} is testing Github Actions
on: 
  workflow_dispatch:
  push:
    branches:
      - main
env:
  RUN_BY: yashraj
jobs:
  demo:
    runs-on: self-hosted
    steps:
      - run: echo "Hello World!!! Github Actions"
      - run: echo "Event name -> ${{ github.event_name }}"
      - run: echo "OS -> ${{ runner.os }} "
      - run: echo "Branch -> ${{ github.ref }}"
      - run: echo "Repository -> ${{ github.repository }}"
      - name: checkout repo code
        uses: actions/checkout@v3
      - run: ls -al
      - run: echo "Job Status -> ${{ job.status }}"
